# Generated by Django 4.2.1 on 2023-06-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheCafeteriaAPI', '0009_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
