# Generated by Django 4.2.1 on 2023-06-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheCafeteriaAPI', '0010_address_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='selected',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
