# Generated by Django 4.2.1 on 2023-06-21 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TheCafeteriaAPI', '0011_alter_address_selected'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TheCafeteriaAPI.address')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheCafeteriaAPI.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
